# Generated by Django 2.2 on 2020-12-08 10:46

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('about_us_content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='درباره ما')),
                ('about_damir_content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='درباره دمیر')),
                ('buy_from_damir', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='خرید از دمیر')),
                ('sell_in_damir', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='فروش در دمیر')),
                ('terms_and_conditions', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='قوانین و مقررات')),
                ('privacy_and_policy', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='شرایط خصوصی')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10240132, null=True)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='ایونت خاص یا هر چیز دیگری', max_length=225, null=True)),
                ('slider_image', models.ImageField(upload_to='')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsTellerEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
