# Generated by Django 2.2 on 2020-12-08 12:02

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_auto_20201208_1531'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='نام پست')),
                ('short_description', models.TextField(verbose_name='توضیح پیش نمایش')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن پست')),
                ('timestamp', models.DateField(auto_now=True, verbose_name='تاریخ ثبت پست')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='تصویر پست')),
                ('image_alt', models.CharField(max_length=600, verbose_name='seo image alternatinve')),
                ('featured', models.BooleanField(default=False)),
                ('active_post', models.BooleanField(default=True)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('avg_read', models.FloatField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(to='categories.Category', verbose_name='دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('username', models.CharField(max_length=164)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
